version: '2'

services:
  sensor-pm25:
    image: localtest/rpi-mqtt-pm25
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - PM25_THRESHOLD=54
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/pm

  sensor-rain:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=17
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/rain
     - SIGNAL_DO=0

  sensor-camera-ctl:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=5
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/camera
     - SIGNAL_DO=1

  sensor-light:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=23
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/light
     - SIGNAL_DO=1

  sensor-infrared:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=24
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/infrared
     - SIGNAL_DO=1

  camera:
    image: localtest/rpi-mqtt-capture
    privileged: true
    restart: always
    network_mode: bridge
    volumes:
     - /home/pi/photo:/root/photo
    depends_on:
     - sensor-camera-ctl
    environment:
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/camera

  led:
    image: localtest/rpi-mqtt-subscriber
    privileged: true
    restart: always
    network_mode: bridge
    depends_on:
     - sensor-pm25
     - sensor-rain
     - sensor-camera-ctl
     - sensor-light
     - sensor-infrared
    environment:
     - GPIO_PIN=26
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/#

