version: '2'

services:
  sensor-pm25:
    image: localtest/rpi-mqtt-pm25
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - PM25_THRESHOLD=54
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/pm

  sensor-rain:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=17
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/rain
     - SIGNAL_DO=1

  sensor-camera-button:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=5
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/camera
     - SIGNAL_DO=1

  sensor-light:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=23
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/light
     - SIGNAL_DO=1

  sensor-infrared:
    image: localtest/rpi-mqtt-publisher
    privileged: true
    restart: always
    network_mode: bridge
    environment:
     - GPIO_PIN=24
     - MQTT_BROKER=192.168.10.245
     - MQTT_PORT=1883
     - MQTT_KEEPALIVE_INTERVAL=60
     - MQTT_TOPIC=smartlamp/infrared
     - SIGNAL_DO=1
